services:
  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: hermes-redis-prod 
    env_file:
      - hermes/env.production
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379" # Only bind to localhost
    volumes:
      - redis_data:/data
    networks:
      - hermes-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
   
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Django Backend (Production)
  django-web:
    build:
      context: ./hermes
      dockerfile: Dockerfile.prod
    container_name: hermes-django-prod
    ports:
      - "127.0.0.1:8000:8000" # Only bind to localhost
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - hermes/env.production
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - logs_volume:/app/logs
    networks:
      - hermes-network
    restart: unless-stopped
    command: >
      sh -c "python manage.py collectstatic --noinput && \
             gunicorn --bind 0.0.0.0:8000 --workers 4 --worker-class sync --max-requests 1000 --max-requests-jitter 100 --timeout 30 --keep-alive 2 --preload hermes.wsgi:application"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"

  # React Frontend (Production)
  react-frontend:
    build:
      context: ../OlympReact/hermes
      dockerfile: Dockerfile.prod
    container_name: hermes-react-prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      django-web:
        condition: service_healthy
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - static_volume:/usr/share/nginx/html/static:ro
    command: >
      sh -c "
        chown nginx:nginx /etc/nginx/ssl/cert.pem /etc/nginx/ssl/key.pem 2>/dev/null || true &&
        chmod 644 /etc/nginx/ssl/cert.pem 2>/dev/null || true &&
        chmod 600 /etc/nginx/ssl/key.pem 2>/dev/null || true &&
        nginx -g 'daemon off;'
      "
    networks:
      - hermes-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.25"

  # Note: React frontend already includes nginx and serves on ports 80/443
  # No separate nginx container needed

  # Monitoring - Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: hermes-prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    networks:
      - hermes-network
    restart: unless-stopped

  # Monitoring - Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: hermes-grafana
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    networks:
      - hermes-network
    restart: unless-stopped
    env_file:
      - hermes/env.production

volumes:
  redis_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local
  logs_volume:
    driver: local
  # nginx_logs volume removed - not needed since React frontend includes nginx
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  hermes-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
