# Generated by Django 5.1.1 on 2024-10-08 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_value_1', models.FloatField()),
                ('test_value_2', models.FloatField()),
                ('test_value_3', models.FloatField()),
                ('test_value_4', models.FloatField()),
                ('test_value_5', models.FloatField()),
                ('test_value_6', models.FloatField()),
                ('test_value_7', models.FloatField()),
                ('test_value_8', models.FloatField()),
                ('points', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
