# Generated by Django 5.1.1 on 2025-07-26 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(choices=[('M', 'Muž'), ('F', 'Žena')], default='M', max_length=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_people', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.team')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.team')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(auto_now_add=True)),
                ('test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('strength_score', models.FloatField(blank=True, null=True)),
                ('speed_score', models.FloatField(blank=True, null=True)),
                ('endurance_score', models.FloatField(blank=True, null=True)),
                ('agility_score', models.FloatField(blank=True, null=True)),
                ('ladder_score', models.IntegerField(default=0)),
                ('ladder_time_1', models.FloatField(blank=True, null=True)),
                ('ladder_time_2', models.FloatField(blank=True, null=True)),
                ('hexagon_score', models.IntegerField(default=0)),
                ('hexagon_time_cw', models.FloatField(blank=True, null=True)),
                ('hexagon_time_ccw', models.FloatField(blank=True, null=True)),
                ('y_test_score', models.IntegerField(default=0)),
                ('y_test_index', models.FloatField(blank=True, null=True)),
                ('y_test_ll_front', models.FloatField(blank=True, null=True)),
                ('y_test_ll_left', models.FloatField(blank=True, null=True)),
                ('y_test_ll_right', models.FloatField(blank=True, null=True)),
                ('y_test_rl_front', models.FloatField(blank=True, null=True)),
                ('y_test_rl_right', models.FloatField(blank=True, null=True)),
                ('y_test_rl_left', models.FloatField(blank=True, null=True)),
                ('y_test_la_left', models.FloatField(blank=True, null=True)),
                ('y_test_la_front', models.FloatField(blank=True, null=True)),
                ('y_test_la_back', models.FloatField(blank=True, null=True)),
                ('y_test_ra_right', models.FloatField(blank=True, null=True)),
                ('y_test_ra_front', models.FloatField(blank=True, null=True)),
                ('y_test_ra_back', models.FloatField(blank=True, null=True)),
                ('brace_score', models.IntegerField(default=0)),
                ('brace_time_1', models.FloatField(blank=True, null=True)),
                ('brace_time_2', models.FloatField(blank=True, null=True)),
                ('medicimbal_score', models.IntegerField(default=0)),
                ('medicimbal_throw_1', models.FloatField(blank=True, null=True)),
                ('medicimbal_throw_2', models.FloatField(blank=True, null=True)),
                ('medicimbal_throw_3', models.FloatField(blank=True, null=True)),
                ('jet_score', models.IntegerField(default=0)),
                ('jet_laps', models.IntegerField(blank=True, null=True)),
                ('jet_sides', models.IntegerField(blank=True, null=True)),
                ('jet_distance', models.IntegerField(blank=True, null=True)),
                ('triple_jump_score', models.IntegerField(default=0)),
                ('triple_jump_distance_1', models.FloatField(blank=True, null=True)),
                ('triple_jump_distance_2', models.FloatField(blank=True, null=True)),
                ('triple_jump_distance_3', models.FloatField(blank=True, null=True)),
                ('beep_test_score', models.IntegerField(default=0)),
                ('beep_test_level', models.IntegerField(blank=True, null=True)),
                ('beep_test_laps', models.IntegerField(blank=True, null=True)),
                ('beep_test_total_laps', models.IntegerField(blank=True, null=True)),
                ('max_hr', models.IntegerField(blank=True, null=True)),
                ('active_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='tests.activetest')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.person')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.team')),
            ],
        ),
    ]
