# Generated by Django 5.1.1 on 2024-10-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='person_name',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
