# Generated by Django 5.1.1 on 2025-07-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_testresult_active_test_event_testresult_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='beep_test_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
