# Generated by Django 5.1.1 on 2025-07-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_personmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_birth_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='gender_required',
            field=models.BooleanField(default=False),
        ),
    ]
