# Generated by Django 5.1.1 on 2024-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_testresult_beep_test_laps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='person_name',
            field=models.CharField(max_length=100),
        ),
    ]
