# Generated by Django 5.1.1 on 2024-10-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_profile_user_alter_profile_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='hexagon_time_l',
            new_name='hexagon_time_ccw',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='hexagon_time_r',
            new_name='hexagon_time_cw',
        ),
    ]
