# Generated by Django 5.1.1 on 2025-07-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_person_date_of_birth_required_person_gender_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
