# Generated by Django 5.1.1 on 2024-10-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_rename_y_test_lf_front_testresult_y_test_ll_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='y_test_index',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
