# Generated by Django 5.1.1 on 2024-10-31 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_alter_testresult_beep_test_laps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tests.profile'),
            preserve_default=False,
        ),
    ]
