# Generated by Django 5.1.1 on 2024-10-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_testresult_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='person_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='tst', max_length=100),
            preserve_default=False,
        ),
    ]
