# Generated by Django 5.1.1 on 2024-10-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_rename_person_name_profile_name_profile_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sex',
            new_name='gender',
        ),
    ]
