# Generated by Django 5.1.3 on 2024-11-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0016_testresult_agility_score_testresult_endurance_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="test_date",
            field=models.DateField(auto_now_add=True, default="2024-11-24"),
            preserve_default=False,
        ),
    ]
