# Generated by Django 5.1.3 on 2024-11-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_remove_testresult_test_name_alter_testresult_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
